#!/usr/bin/env bash
#
# sync_video_player_fork.sh
#
# One-way mirror of the patched video_player federation:
#
#     SOURCE OF TRUTH                          GENERATED MIRROR
#     mhmdfathy96/packages                     mhmdfathy96/video_player_forwardbuffer
#     (flutter monorepo fork, holds the   -->  (tiny standalone repo the app's
#      upstream PR branch)                      pubspec dependency_overrides pull)
#
# Why this exists: the app pulls video_player from the SMALL repo so `flutter
# pub get` / CI clones stay fast (the full monorepo is huge). But the patch's
# real home is the monorepo fork, because that's what the upstream Flutter PR
# tracks. This script copies the four packages we use from the fork into the
# small repo so you only ever edit ONE place (the fork) and run this to publish.
#
# It is a STRICT mirror: files present in the small repo but not in the fork's
# package folders are deleted (repo-root files like PATCH.md / README are left
# untouched — only the four package folders are synced).
#
# This script lives in the MIRROR repo. Run it from this repo's root after you
# have committed + pushed your patch to the source fork.
#
# Usage (from the root of this repo):
#   ./sync_video_player_fork.sh             # sync + commit + push the mirror
#   ./sync_video_player_fork.sh --dry-run   # show what would change, touch nothing
#
# Auth: uses your existing git credentials. You need push access to the mirror
# repo (you already do — the app consumes it).
#
# Requirements: git >= 2.25 (sparse checkout), rsync.

set -euo pipefail

# ----- config (override via env vars if branches/repos ever change) ----------
SRC_REPO="${SRC_REPO:-https://github.com/mhmdfathy96/packages.git}"
SRC_BRANCH="${SRC_BRANCH:-video_player_forward_buffer_duration}"
SRC_SUBDIR="${SRC_SUBDIR:-packages/video_player}"   # where the packages live in the fork

DST_REPO="${DST_REPO:-https://github.com/mhmdfathy96/video_player_forwardbuffer.git}"
DST_BRANCH="${DST_BRANCH:-main}"
DST_SUBDIR="${DST_SUBDIR:-packages}"                 # where they live in the mirror

# Packages to mirror (same folder name on both sides; video_player_web is skipped).
PACKAGES=(
  video_player
  video_player_platform_interface
  video_player_android
  video_player_avfoundation
)

# Heavy dirs a pub CONSUMER never needs. Excluding them keeps the mirror tiny —
# the whole reason the small repo exists (fast `flutter pub get` / CI clones).
# These are also protected from --delete, so they're never re-added to the mirror.
EXCLUDES=(
  'example/'
  'test/'
  'integration_test/'
)
# -----------------------------------------------------------------------------

DRY_RUN=0
[[ "${1:-}" == "--dry-run" || "${1:-}" == "-n" ]] && DRY_RUN=1

for bin in git rsync; do
  command -v "$bin" >/dev/null 2>&1 || { echo "error: '$bin' is required but not found" >&2; exit 1; }
done

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
SRC_DIR="$WORK/src"
DST_DIR="$WORK/dst"

echo "==> Cloning source (sparse): $SRC_REPO @ $SRC_BRANCH"
git clone --quiet --no-checkout --depth 1 --filter=blob:none \
  --branch "$SRC_BRANCH" --single-branch "$SRC_REPO" "$SRC_DIR"
git -C "$SRC_DIR" sparse-checkout set --no-cone "$SRC_SUBDIR" >/dev/null
git -C "$SRC_DIR" checkout --quiet
SRC_SHA="$(git -C "$SRC_DIR" rev-parse --short HEAD)"
echo "    source at $SRC_SHA"

echo "==> Cloning mirror: $DST_REPO @ $DST_BRANCH"
git -C "$WORK" clone --quiet --depth 1 --branch "$DST_BRANCH" --single-branch "$DST_REPO" dst

# --checksum: compare by content, not mtime (independent clones always have
# fresh mtimes, which would otherwise make every file look changed).
RSYNC_FLAGS=(-a --checksum --delete --exclude='.git')
for ex in "${EXCLUDES[@]}"; do RSYNC_FLAGS+=(--exclude="$ex"); done
[[ "$DRY_RUN" == 1 ]] && RSYNC_FLAGS+=(-n -v)

echo "==> Mirroring ${#PACKAGES[@]} package(s):"
for p in "${PACKAGES[@]}"; do
  src="$SRC_DIR/$SRC_SUBDIR/$p/"
  dst="$DST_DIR/$DST_SUBDIR/$p/"
  if [[ ! -d "$src" ]]; then
    echo "error: expected source package not found: $src" >&2
    exit 1
  fi
  mkdir -p "$dst"
  echo "    - $p"
  rsync "${RSYNC_FLAGS[@]}" "$src" "$dst"
done

if [[ "$DRY_RUN" == 1 ]]; then
  echo "==> Dry run complete. Nothing was committed or pushed."
  exit 0
fi

if [[ -z "$(git -C "$DST_DIR" status --porcelain)" ]]; then
  echo "==> Mirror already up to date with source $SRC_SHA. Nothing to do."
  exit 0
fi

echo "==> Committing and pushing mirror update"
git -C "$DST_DIR" add -A
git -C "$DST_DIR" -c user.name="$(git config user.name || echo sync-bot)" \
  -c user.email="$(git config user.email || echo sync@local)" \
  commit --quiet -m "sync: mirror video_player from packages fork @ $SRC_SHA

Generated by tool/sync_video_player_fork.sh — do not edit packages here by hand.
Source: $SRC_REPO ($SRC_BRANCH @ $SRC_SHA)"
git -C "$DST_DIR" push --quiet origin "$DST_BRANCH"

echo "==> Done. $DST_REPO @ $DST_BRANCH now matches $SRC_SHA."
echo "    Run 'flutter pub get' in the app to pick up the new mirror commit."
